In [1]:
"""1. Write a NumPy program to print the NumPy version on your system."""

import numpy as np

print(np.__version__)

1.25.0


In [2]:
"""2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]"""

import numpy as np

a = [12.23, 13.32, 100, 36.32]
print(np.array(a))

[ 12.23  13.32 100.    36.32]


In [2]:
"""3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]"""

import numpy as np

print(np.arange(2, 11).reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
"""4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]"""

import numpy as np

x = np.zeros(10)

print(x)

x[5] = 11

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [6]:
"""5. Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]"""

import numpy as np

print(np.arange(12, 38))

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [7]:
"""6. Write a NumPy program to reverse an array (the first element becomes the last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]"""

import numpy as np

print(np.arange(12, 38))
print(np.arange(12, 38)[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [3]:
"""7. Write a NumPy program to convert an array to a floating type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]"""

import numpy as np

print(np.asfarray([1, 2, 3, 4]))

[1. 2. 3. 4.]
