In [33]:
"""59. Write a NumPy program to multiply two given arrays of the same size element-by-element."""
import numpy as np 
from numpy import random

def get_random_int_list(max_ = 100, size = 5):
    return random.randint(max_, size = size)

print(np.multiply(np.array([get_random_int_list(), get_random_int_list()]), np.array([get_random_int_list(), get_random_int_list()])))

[[ 650    0   10  871  650]
 [6384 2856 6696 5640 2813]]


In [37]:
"""52. Write a NumPy program to sort a given array by row and column in ascending order."""

import numpy as np  

def get_random_int_list(max_ = 100, size = 5):
    return random.randint(max_, size = size)


n = np.array([get_random_int_list(), get_random_int_list()])

print(np.sort(n))
print(np.sort(n, axis = 0))

[[21 24 30 37 41]
 [29 54 64 90 93]]
[[41 37 30 21 24]
 [54 93 90 29 64]]


In [38]:
"""51. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros."""

import numpy as np

print(np.zeros(shape = (5, 6), dtype = 'int'))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
