In [7]:
"""1. Write a NumPy program to compute the multiplication of two given matrixes."""

import numpy as np

def get_random_int_list(max_ = 100, size = 2):
    return np.random.randint(max_, size = size)

print(np.dot([get_random_int_list(), get_random_int_list()], [get_random_int_list(), get_random_int_list()]))

[[1892 4770]
 [3916 5510]]


In [8]:
"""2. Write a NumPy program to compute the outer product of two given vectors."""

import numpy as np

def get_random_int_list(max_ = 100, size = 2):
    return np.random.randint(max_, size = size)

print(np.outer([get_random_int_list(), get_random_int_list()], [get_random_int_list(), get_random_int_list()]))

[[ 232 1450 1305  580]
 [ 464 2900 2610 1160]
 [ 792 4950 4455 1980]
 [ 464 2900 2610 1160]]
