In [1]:
"""1. Write a NumPy program to generate five random numbers from the normal distribution.
Expected Output:
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]"""

from numpy import random

print(random.normal(size = 5))

[ 0.04966038  0.97221474  2.19735629 -0.51412839 -0.36355858]


In [2]:
"""2. Write a NumPy program to generate six random integers between 10 and 30.
Expected Output:
[20 28 27 17 28 29]"""

from numpy import random

print(random.randint(low = 10, high = 30, size = 6))

[12 19 20 11 23 25]


In [5]:
"""17. Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255)."""

import numpy as np
from numpy import random

print(random.randint(low = 0, high = 256, size = (300, 400, 5)))

[[[102  58 141 209  44]
  [223 216 253  80 179]
  [134 108  92 144 231]
  ...
  [ 58 163 182 166 226]
  [ 99 169   1 197  54]
  [205 200 224 195  64]]

 [[ 24 193  77  87 221]
  [ 85 254   5 172 163]
  [129 120 254 235 132]
  ...
  [  2 101  64  94  99]
  [252  72 225  63  81]
  [ 51 242 165 111 232]]

 [[166 186   3 217 199]
  [ 83 184 244 145 116]
  [ 99 205 199 241 121]
  ...
  [127  56 209 189 144]
  [104 253  43 200 154]
  [205  52  97 220  84]]

 ...

 [[180 225 210  85 187]
  [ 19 137 148 159 135]
  [191 220 142  30 250]
  ...
  [ 49 197 130  20 233]
  [145  38  64 223 180]
  [ 10  52 219  16 226]]

 [[155 188 137  81 104]
  [ 21  96 179  59  24]
  [212  66  52 249 249]
  ...
  [250   2 126 223  52]
  [224  83 128 107 250]
  [153  17   9 110 223]]

 [[ 51 165  37  73   3]
  [ 58  48   3 236  72]
  [ 89 137 231 238 123]
  ...
  [107  99 146 161  95]
  [254  71 221 156 181]
  [ 94 138  45  16 235]]]


In [12]:
"""6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
Sample Output:
[5 7 9 0 2 3 1 6 8 4]
Same result using permutation():
[6 7 4 5 8 2 3 9 0 1]"""

import numpy as np
from numpy import random

x = np.arange(10)
random.shuffle(x)
print(x)
print(random.permutation(10))

[4 3 1 9 2 8 5 7 6 0]
[6 5 7 2 1 4 3 9 0 8]
