In [1]:
"""1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.
Expected Output:
Original array:
[[10 40]
[30 20]]
Sort the array along the first axis:
[[10 20]
[30 40]]
Sort the array along the last axis:
[[10 40]
[20 30]]
Sort the flattened array:
[10 20 30 40]"""

import numpy as np

a = np.array([[10, 40], [30, 20]])
print(np.sort(a, axis = 0))
print(np.sort(a))
print(np.sort(a, axis = None))

[[10 20]
 [30 40]]
[[10 40]
 [20 30]]
[10 20 30 40]
